// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

type User struct {
	ID        int32       `json:"id"`
	Name      string      `json:"name"`
	Role      string      `json:"role"`
	CreatedAt interface{} `json:"created_at"`
	UpdatedAt interface{} `json:"updated_at"`
}
