// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

type RefreshToken struct {
	Token     string      `json:"token"`
	CreatedAt interface{} `json:"created_at"`
	UpdatedAt interface{} `json:"updated_at"`
	UserID    int32       `json:"user_id"`
	ExpiresAt interface{} `json:"expires_at"`
	RevokedAt interface{} `json:"revoked_at"`
}

type User struct {
	ID             int32       `json:"id"`
	Name           string      `json:"name"`
	Role           string      `json:"role"`
	CreatedAt      interface{} `json:"created_at"`
	UpdatedAt      interface{} `json:"updated_at"`
	HashedPassword string      `json:"hashed_password"`
}
